"""name change personalgifcollections

Revision ID: 5623a774c7e3
Revises: 574ca11f7357
Create Date: 2018-03-19 12:48:46.743434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5623a774c7e3'
down_revision = '574ca11f7357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    op.drop_constraint('searches_gif_id_fkey', 'searches', type_='foreignkey')
    op.drop_constraint('searches_searches_id_fkey', 'searches', type_='foreignkey')
    op.drop_column('searches', 'searches_id')
    op.drop_column('searches', 'gif_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('gif_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('searches', sa.Column('searches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('searches_searches_id_fkey', 'searches', 'searches', ['searches_id'], ['id'])
    op.create_foreign_key('searches_gif_id_fkey', 'searches', 'gifs', ['gif_id'], ['id'])
    op.create_table('collections',
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gif_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name='collections_collection_id_fkey'),
    sa.ForeignKeyConstraint(['gif_id'], ['gifs.id'], name='collections_gif_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='collections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    # ### end Alembic commands ###
