"""many manys

Revision ID: 574ca11f7357
Revises: 
Create Date: 2018-03-19 11:57:19.542091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574ca11f7357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gif_collections')
    op.drop_table('gif')
    op.drop_table('personal_gif_collection')
    op.drop_table('collection')
    op.drop_table('search_term')
    op.add_column('collections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'user_id')
    op.create_table('search_term',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_term_pkey'),
    sa.UniqueConstraint('term', name='search_term_term_key')
    )
    op.create_table('collection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='collection_pkey')
    )
    op.create_table('personal_gif_collection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='personal_gif_collection_pkey')
    )
    op.create_table('gif',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('embedURL', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gif_pkey')
    )
    op.create_table('gif_collections',
    sa.Column('gif_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gif_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gif_collection_id'], ['gif_collections.id'], name='gif_collections_gif_collection_id_fkey'),
    sa.ForeignKeyConstraint(['gif_id'], ['gifs.id'], name='gif_collections_gif_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gif_collections_pkey')
    )
    # ### end Alembic commands ###
